version: '2.29.1'

services:
  node-server:
    build:
      context: ./backend-server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${NODE_SERVER_PORT}:${NODE_SERVER_PORT}