services:
  node-server:
    build:
      context: ../
      dockerfile: ./better-backend/backend-server/Dockerfile
    env_file:
      - ../.env.server
    ports:
      - ${NODE_SERVER_PORT}:${NODE_SERVER_PORT}